import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import 'tailwindcss/tailwind.css'
import styles from '../styles/Home.module.css'
import NextLink from 'next/link';
import Login from './Login'
import Layout from '../components/Layout'
import Router from 'next/router'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [loaded,setLoaded] = useState(false)
  useEffect(() => {
      const {pathname} = Router
      // conditional redirect
      try{
      if(pathname == '/'  ){
          // with router.push the page may be added to history
          // the browser on history back will  go back to this page and then forward again to the redirected page
          // you can prevent this behaviour using location.replace
          Router.push('/Login')
         //location.replace("/hello-nextjs")
      }

      
      if(localStorage.getItem('token')==null)
      {
        Router.push('/Login')
      }}
      catch(err){
        Router.push('/Login')
      }
    
    },[]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
    </>
  )
}
